
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8800/postgres
    username: postgres
    password: "yourpass"
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db
    baseline-on-migrate: true
server:
  port: 7833

